Repository Mika-Rsbg/Budget-Planner, pull requests merged in 2025-05, with the labels that each got.

#6 Docs/readme GUI plugin update
  docs/README_GUI_PLUGIN.md
  src/gui/plugins/menu_extension/plugin_all_menu_help.py
Labels: documentation

#8 ✨ Add AI-based budget suggestions feature
  src/gui/budget_suggestion/__init__.py
  src/gui/budget_suggestion/suggestion_dialog.py
  src/gui/homepage/homepage.py
  src/utils/ai/__init__.py
  src/utils/ai/budget_suggestions.py
Labels: enhancement

#14 Add Logging and Replace Print Statements
  .gitignore
  src/gui/accountpage/name_input_page.py
  src/gui/basetoplevelwindow.py
  src/gui/basewindow.py
  src/gui/budget_suggestion/suggestion_dialog.py
  src/gui/homepage/homepage.py
  src/gui/plugins/__init__.py
  src/main.py
  src/utils/ai/budget_suggestions.py
  src/utils/data/createdatabase_utils.py
  src/utils/data/database/account_utils.py
  src/utils/data/database/counterparty_utils.py
  src/utils/data/database/transaction_typ_utils.py
  src/utils/data/database/transaction_utils.py
  src/utils/data/database_connection.py
  src/utils/data/date_utils.py
  src/utils/data/mt940import_utils.py
  src/utils/logging/clean_up_log.py
  src/utils/logging/logger_config.py
  src/utils/logging/logging_tools.py
Labels: enhancement

#18 Feat/improve flake8 logging compatibility pr#8
  src/gui/budget_suggestion/__init__.py
  src/gui/budget_suggestion/suggestion_dialog.py
  src/utils/ai/budget_suggestions.py
  src/utils/logging/logging_tools.py
Labels: legacy code, code review

#21 Fix/bug mt940 import fails when currency marker is not cr or dr #11
  src/utils/data/mt940import_utils.py
Labels: bug
